# Generated by Django 4.1.7 on 2023-05-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realblog1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_blog',
            options={'verbose_name_plural': 'my_blog'},
        ),
    ]
