# Generated by Django 4.1.7 on 2023-06-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog1', '0002_alter_my_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'conatact us',
            },
        ),
    ]
