# Generated by Django 4.1.7 on 2023-06-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog1', '0003_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
