# Generated by Django 4.1.7 on 2023-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realblog1', '0004_alter_contact_us_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comm', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
    ]
