# Generated by Django 4.1.7 on 2023-06-10 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realblog1', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blog',
            name='des',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
